spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: haihai211
    url: jdbc:mysql://gz-cdb-6vny9hzq.sql.tencentcdb.com:62636/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
  port: 8085





















#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: C:\Apps\log
#  file: C:\Apps\log\sell.log
#  level:
#    com.persistence.sell.LoggerTest: debug